export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const CLOSE_DROPDOWN = "CLOSE_DROPDOWN";
export const OPEN_DROPDOWN = "OPEN_DROPDOWN";
export const CHANGE_HEADING = "CHANGE_HEADING";
export const OPEN_TOP_DRAWER = "OPEN_TOP_DRAWER";
export const CLOSE_TOP_DRAWER = "CLOSE_TOP_DRAWER";
